dict = {
    "grp_warn_no_reason":       "❗️️ {} has been warned [{}/{}].",
    "grp_warn_reason":          "❗️️ {} has been warned [{}/{}] for <b>{}</b>",
    "log_warn_reason":          "❗️ <b>Warn</b>\nTo: {}\nBy: {}\nReason: {}\nUser Warns Now: {}/{}",
    "log_warn_no_reason":       "❗️ <b>Warn</b>\nTo: {}\nBy: {}\nUser Warns Now: {}/{}",
    "log_new_user":             "➕ <b>New User</b>\n-> {}",
    "grp_ban_reason":           "🚷 {} has been banned for {}.",
    "log_ban_reason":           "🚷 <b>Ban</b>\nTo: {}\nBy: {}\nReason: {}",
    "grp_ban_no_reason":        "🚷 {} has been banned.",
    "log_ban_no_reason":        "🚷 <b>Ban</b>\nTo: {}\nBy: {}",
    "grp_mute_custom":          "🔇 {} has been muted for {} hours.",
    "log_mute_custom":          "🔇 <b>Mute</b>\nTo: {}\nBy: {}\nHours: {}",
    "grp_mute_default":         "🔇 {} has been muted for <b>{}</b> until the next hour.",
    "log_mute_default":         "🔇 <b>Mute</b>\nTo: {}\nBy: {}\nReason: {}\nHours: 1",
    "grp_kick_reason":          "❕ {} has been kicked for <b>{}</b>.",
    "log_kick_reason":          "❕ <b>Kick</b>\nTo: {}\nBy: {} \nReason: {}",
    "grp_kick_no_reason":       "❕ {} has been kicked.",
    "log_kick_no_reason":       "❕ <b>Kick</b>\nTo: {}\nBy: {}",
    "grp_unban":                "✅ {} unbanned.",
    "log_unban":                "✅ <b>Unban</b>\nTo: {}\nBy: {}",
    "grp_unwarn":               "❎ {} unwarned.\nHe now has {} warns.",
    "log_unwarn":               "❎ <b>Unwarn</b>\nTo: {}\nBy: {} \nUser Warns Now: {}/{}",
    "grp_unmute":               "🔊 {} unmuted.",
    "log_unmute":               "🔊 <b>Unmute</b>\nTo: {} \nBy: {}",
    "grp_info":                 "🙍‍♂️ <b>User Info</b>\nUser: {}\nChatID: <code>{}</code>\nWarns: {}",
    "grp_new_helper":           "⛑ {} is now <b>Helper</b>.",
    "log_new_helper":           "⛑ <b>New Helper</b>\nTo: {}\nBy: {}",
    "grp_rem_helper":           "⛑ {} removed from <b>Helpers</b>.",
    "log_rem_helper":           "⛑ <b>Removed Helper</b>\nTo: {}\nBy: {}",
    "grp_new_moderator":        "👷🏻 {} is now <b>Moderator</b>.",
    "log_new_moderator":        "👷🏻 <b>New Moderator</b>\nTo: {}\nBy: {}",
    "grp_rem_moderator":        "👷🏻 {} removed from <b>Moderators</b>.",
    "log_rem_moderator":        "👷🏻 <b>Removed Moderator</b>\nTo: {}\nBy: {}",
    "grp_new_manager":          "🛃 {} is now <b>Manager</b>.",
    "log_new_manager":          "🛃 <b>New Manager</b>\nTo: {}\nBy: {}",
    "grp_rem_manager":          "🛃 {} removed from <b>Managers</b>.",
    "log_rem_manager":          "🛃 <b>Removed Manager</b>\nTo: {}\nBy: {}",
    "bot_reload":               "✅ <b>Bot reloaded!</b>\nBy: {}",
    "bot_start_inactive_kick":  "☢️ <b>Inactive Users Kick</b>\nStarted By: {}\nMax. Inactive days: {}",
    "bot_end_inactive_kick":    "☢️ <b>Inactive Users Kick terminated!</b>",
    "str_max_warns":            "Exceeded max warns",
    "grp_staff_call":           "🆘 <i>Call received.</i>",
    "log_staff_call_reply":     "🆘 <b>Staff Call</b>\nBy: {}\nTo: {}\nMessage: {}",
    "log_staff_call_noreply":   "🆘 <b>Staff Call</b>\nBy: {}\nMessage: {}",
    "grp_staff_title":          "🔰️ <b>GROUP STAFF</b> 🔰️",
    "grp_staff_founder":        "\n\n  👑 <b>Founder</b>",
    "grp_staff_admins":         "\n\n  👮🏼 <b>Admins</b>",
    "grp_staff_moderators":     "\n\n  👷🏻 <b>Moderators</b>",
    "grp_staff_managers":       "\n\n  🛃 <b>Managers</b>",
    "grp_staff_helpers":        "\n\n  ⛑ <b>Helpers</b>",
    "grp_set_username":         "🌐  {}, please, set an <b>username</b> in Telegram Settings",
    "grp_scan_file":            "<i>Scanning File...</i>",
    "grp_scanned_safe":         "✅ File Scan: Safe\nAlert {}/{}",
    "grp_scanned_warning":      "⚠️ File Scan: Warning\nAlert {}/{}",
    "grp_scanned_malware":      "🛑️ File Scan: Malware\nAlert {}/{}",
    "grp_shorter_name":         "🌐 {}, please, set a <b>shorter name</b> in Telegram Settings.",
    "log_blacklist_word":       "🆎 <b>Blacklisted Word</b>\nBy: {}",
    "str_forward":              "Forwarding from a non whitelisted channel",
    "str_porn":                 "Porn media",
    "str_offensive":            "Offensive media",
    "grp_global_silence_on":    "🔇 <b>Global Silence activated!</b>\nNow, only the group staff can write messages.",
    "log_global_silence_on":    "🔇 <b>Global Silence On</b>\nBy: {}",
    "grp_global_silence_off":   "🔊 <b>Global Silence deactivated!</b>\nNow, all users can write messages.",
    "log_global_silence_off":   "🔊 <b>Global Silence Off</b>\nBy: {}",
    "cmd_helper":               "/helper",
    "cmd_unhelper":             "/unhelper",
    "cmd_mod":                  "/mod",
    "cmd_unmod":                "/unmod",
    "cmd_manager":              "/manager",
    "cmd_unmanager":            "/unmanager",
    "cmd_tell":                 "/tell",
    "cmd_reload":               "/reload",
    "cmd_kickinactive":         "/kickinactive",
    "cmd_warn":                 "/warn",
    "cmd_delwarn":              "/delwarn",
    "cmd_mute":                 "/mute",
    "cmd_kick":                 "/kick",
    "cmd_ban":                  "/ban",
    "cmd_unban":                "/unban",
    "cmd_unwarn":               "/unwarn",
    "cmd_unmute":               "/unmute",
    "cmd_info":                 "/info",
    "cmd_silenceon":            "/silenceon",
    "cmd_silenceoff":           "/silenceoff",
    "cmd_del":                  "/del",
    "cmd_staff":                "/staff",
    "cmd_rules":                "/rules"
}
