dict = {
    "grp_warn_no_reason":       "❗️️ {} è stato ammonito [{}/{}].",
    "grp_warn_reason":          "❗️️ {} è stato ammonito [{}/{}] per <b>{}</b>",
    "log_warn_reason":          "❗️ <b>Warn</b>\nA: {}\Di: {} {}\Motivo: {}\Ammonizioni utente: {}/{}",
    "log_new_user":             "<b>Nuovo utente</b>\n-> <a href=\"tg://user?id={}>{}</a>",
    "grp_ban_reason":           "🚷 {} è stato bannato per {}.",
    "log_ban_reason":           "🚷 <b>Ban</b>\nA: {}\nDi: {} {}\Motivo: {}",
    "grp_ban_no_reason":        "🚷 {} è stato bannato.",
    "log_ban_no_reason":        "🚷 <b>Ban</b>\nA: {}\nDi: {} {}",
    "grp_mute_no_reason":       "🔇 {} è stato mutato per un'ora.",
    "log_mute_no_reason":       "🔇 <b>Muta</b>\nA: {}\nDi: {} {}",
    "grp_mute_reason":          "🔇 {} è stato mutato per <b>{}</b> per un'ora.",
    "log_mute_reason":          "🔇 <b>Muta</b>\nTo: {}\nBy: {} {}\nReason: {}",
    "grp_kick_reason":          "❕ {} has been kicked for <b>{}</b>.",
    "log_kick_reason":          "❕ <b>Kick</b>\nA: {}\nBy: {} {} \nReason: {}",
    "grp_kick_no_reason":       "❕ {} has been kicked.",
    "log_kick_no_reason":       "❕ <b>Kick</b>\nTo: {}\nBy: {} {}",
    "grp_unban":                "✅ {} unbanned.",
    "log_unban":                "✅ <b>Unban</b>\nTo: {}\nBy: {} {}",
    "grp_unwarn":               "❎ {} unwarned.\nHe now has {} warns.",
    "log_unwarn":               "❎ <b>Unwarn</b>\nTo: {}\nBy: {} {} \nUser Warns Now: {}/{}",
    "grp_unmute":               "🔊 {} unmuted.",
    "log_unmute":               "🔊 <b>Unmute</b>\nTo: {} \nBy: {} {}",
    "grp_info":                 "🙍‍♂️ <b>User Info</b>\nUser: {}\nChatID: <code>{}</code>\nWarns: {}",
    "grp_new_helper":           "⛑ {} is now <b>Helper</b>.",
    "log_new_helper":           "⛑ <b>New Helper</b>\nTo: {}\nBy: {} {}",
    "grp_rem_helper":           "⛑ {} removed from <b>Helpers</b>.",
    "log_rem_helper":           "⛑ <b>Removed Helper</b>\nTo: {}\nBy: {} {}",
    "grp_new_moderator":        "👷🏻 {} is now <b>Moderator</b>.",
    "log_new_moderator":        "👷🏻 <b>New Moderator</b>\nTo:  {}\nBy: {} {}",
    "grp_rem_moderator":        "👷🏻 {} removed from <b>Moderators</b>.",
    "log_rem_moderator":        "👷🏻 <b>Removed Moderator</b>\nTo: {}\nBy: {} {}",
    "grp_new_manager":          "🛃 {} is now <b>Manager</b>.",
    "log_new_manager":          "🛃 <b>New Manager</b>\nTo: {}\nBy: {} {}",
    "grp_rem_manager":          "🛃 {} removed from <b>Managers</b>.",
    "log_rem_manager":          "🛃 <b>Removed Manager</b>\nTo: {}\nBy: {} {}",
    "bot_reload":               "✅ <b>Bot reloaded!</b>\nBy: {} {}",
    "bot_start_inactive_kick":  "☢️ <b>Inactive Users Kick</b>\nStarted by: {} {}\nMax. Inactive days: {}",
    "bot_end_inactive_kick":    "☢️ <b>Inactive Users Kick terminated!</b>",
    "str_max_warns":            "Exceeded max warns",
    "grp_staff_call":           "🆘 <i>Call received.</i>",
    "log_staff_call_reply":     "🆘 <b>Staff Call</b>\nBy: {}\nTo: {}\nMessage: {}",
    "log_staff_call_noreply":   "🆘 <b>Staff Call</b>\nBy: {}\nMessage: {}",
    "grp_staff_title":          "🔰️ <b>GROUP STAFF</b> 🔰️",
    "grp_staff_founder":        "\n\n  👑 <b>Founder</b>",
    "grp_staff_admins":         "\n\n  👮🏼 <b>Admins</b>",
    "grp_staff_moderators":     "\n\n  👷🏻 <b>Moderators</b>",
    "grp_staff_managers":       "\n\n  🛃 <b>Managers</b>",
    "grp_staff_helpers":        "\n\n  ⛑ <b>Helpers</b>",
    "grp_set_username":         "🌐  {}, please, set an <b>username</b> in Telegram Settings",
    "grp_scan_file":            "<i>Scanning File...</i>",
    "grp_scanned_safe":         "✅ File Scan: Safe\nAlert {}/{}",
    "grp_scanned_warning":      "⚠️ File Scan: Warning\nAlert {}/{}",
    "grp_scanned_malware":      "🛑️ File Scan: Malware\\nAlert {}/{}",
    "grp_shorter_name":         "🌐 {}, please, set a <b>shorter name</b> in Telegram Settings.",
    "log_blacklist_word":       "🆎 <b>Blacklisted Word</b>\nBy: {}"
}
