dict = {
    "grp_warn_no_reason":       "❗️️ {} è stato ammonito [{}/{}].",
    "log_warn_no_reason":       "❗️ <b>Warn</b>\nA: {}\nDi: {}\nAmmonizioni utente: {}/{}",
    "grp_warn_reason":          "❗️️ {} è stato ammonito [{}/{}] per <b>{}</b>",
    "log_warn_reason":          "❗️ <b>Warn</b>\nA: {}\nDi: {}\nMotivo: {}\nAmmonizioni utente: {}/{}",
    "log_new_user":             "➕ <b>Nuovo utente</b>\n-> {}",
    "grp_ban_reason":           "🚷 {} è stato bannato per {}.",
    "log_ban_reason":           "🚷 <b>Ban</b>\nA: {}\nDi: {}\nMotivo: {}",
    "grp_ban_no_reason":        "🚷 {} è stato bannato.",
    "log_ban_no_reason":        "🚷 <b>Ban</b>\nA: {}\nDi: {}",
    "grp_mute_default":         "🔇 {} è stato mutato per un'ora.",
    "log_mute_default":         "🔇 <b>Mute</b>\nA: {}\nDi: {}\nOre: 1",
    "grp_mute_custom":          "🔇 {} è stato mutato per {} ore.",
    "log_mute_custom":          "🔇 <b>Mute</b>\nA: {}\nDi: {}\nOre: {}",
    "grp_kick_reason":          "❕ {} è stato kickato per <b>{}</b>.",
    "log_kick_reason":          "❕ <b>Kick</b>\nA: {}\nDi: {} \nMotivo: {}",
    "grp_kick_no_reason":       "❕ {} è stato kickato.",
    "log_kick_no_reason":       "❕ <b>Kick</b>\nA: {}\nDi: {}",
    "grp_unban":                "✅ {} sbannato.",
    "log_unban":                "✅ <b>Unban</b>\nA: {}\nDi: {}",
    "grp_unwarn":               "❎ {} perdonato.\nOra ha {} ammonizioni.",
    "log_unwarn":               "❎ <b>Unwarn</b>\nA: {}\nDi: {} \nWarn ora: {}/{}",
    "grp_unmute":               "🔊 {} smutato.",
    "log_unmute":               "🔊 <b>Unmute</b>\nA: {} \nDi: {}",
    "grp_info":                 "🙍‍♂️ <b>Informazioni Utente</b>\nUtente: {}\nChatID: <code>{}</code>\nAmmonizioni: {}",
    "grp_new_helper":           "⛑ {} è ora un <b>Helper</b>.",
    "log_new_helper":           "⛑ <b>Nuovo Helper</b>\nA: {}\nDi: {}",
    "grp_rem_helper":           "⛑ {} rimosso dagli <b>Helper</b>.",
    "log_rem_helper":           "⛑ <b>Rimosso Helper</b>\nA: {}\nDi: {}",
    "grp_new_moderator":        "👷🏻 {} è ora un <b>Moderatore</b>.",
    "log_new_moderator":        "👷🏻 <b>Nuovo Moderatore</b>\nA:  {}\nDi: {}",
    "grp_rem_moderator":        "👷🏻 {} rimosso dai <b>Moderatori</b>.",
    "log_rem_moderator":        "👷🏻 <b>Rimosso Moderatore</b>\nA: {}\nDi: {}",
    "grp_new_manager":          "🛃 {} è ora un <b>Gestore</b>.",
    "log_new_manager":          "🛃 <b>Nuovo Gestore</b>\nA: {}\nDi: {}",
    "grp_rem_manager":          "🛃 {} rimosso dai <b>Gestori</b>.",
    "log_rem_manager":          "🛃 <b>Rimosso Gestore</b>\nA: {}\nDi: {}",
    "bot_reload":               "✅ <b>Bot riavviato!</b>",
    "bot_start_inactive_kick":  "☢️ <b>Kick Inattivi</b>\nAvviato da: {}\nGiorni di inattività: {}",
    "bot_end_inactive_kick":    "☢️ <b>Kick Inattivi terminato!</b>",
    "str_max_warns":            "Raggiunto limite ammonizioni.",
    "grp_staff_call":           "🆘 <i>Segnalazione ricevuta.</i>",
    "log_staff_call_reply":     "🆘 <b>Segnalazione</b>\nDi: {}\nVerso: {}\nMessaggio: {}",
    "log_staff_call_noreply":   "🆘 <b>Segnalazione</b>\nDi: {}\nMessaggio: {}",
    "grp_staff_title":          "🔰️ <b>STAFF GRUPPO</b> 🔰️",
    "grp_staff_founder":        "\n\n  👑 <b>Creatore</b>",
    "grp_staff_admins":         "\n\n  👮🏼 <b>Admin</b>",
    "grp_staff_moderators":     "\n\n  👷🏻 <b>Moderatori</b>",
    "grp_staff_managers":       "\n\n  🛃 <b>Gestori</b>",
    "grp_staff_helpers":        "\n\n  ⛑ <b>Helper</b>",
    "grp_set_username":         "🌐  {}, per favore, imposta un <b>username</b> nelle impostazioni di Telegram.",
    "grp_scan_file":            "<i>Scansione File...</i>",
    "grp_scanned_safe":         "✅ Scansione File: Sicuro\nRilevato da {} su {} antivirus.",
    "grp_scanned_warning":      "⚠️ Scansione File: File potenzialmente pericoloso\nRilevato da {} su {} antivirus.",
    "grp_scanned_malware":      "🛑️ Scansione File: Malware\nRilevato da {} su {} antivirus.",
    "grp_shorter_name":         "🌐 {}, per favore, imposta un <b>nome più corto</b> nelle impostazioni di Telegram.",
    "log_blacklist_word":       "🆎 <b>Parola proibita</b>\nDi: {}",
    "str_forward":              "Inoltro da un canale non consentito",
    "str_porn":                 "porno",
    "str_offensive":            "foto offensiva",
    "grp_global_silence_on":    "🔇 <b>Silenzio Globale attivato!</b>\nD'ora in poi, solo lo staff del gruppo potrà scrivere messaggi.",
    "log_global_silence_on":    "🔇 <b>Silenzio Globale ON</b>\nDi: {}",
    "grp_global_silence_off":   "🔊 <b>Silenzio Globale disattivato!</b>\nD'ora in poi, tutti gli utenti potranno inviare messaggi.",
    "log_global_silence_off":   "🔊 <b>Silenzio Globale OFF</b>\nDi: {}",
    "cmd_helper":               "/helper",
    "cmd_unhelper":             "/remhelper",
    "cmd_mod":                  "/mod",
    "cmd_unmod":                "/remmod",
    "cmd_manager":              "/gestore",
    "cmd_unmanager":            "/remgestore",
    "cmd_tell":                 "/annuncio",
    "cmd_reload":               "/riavvia",
    "cmd_kickinactive":         "/kickinattivi",
    "cmd_warn":                 "/warn",
    "cmd_delwarn":              "/delwarn",
    "cmd_mute":                 "/muta",
    "cmd_kick":                 "/kick",
    "cmd_ban":                  "/ban",
    "cmd_unban":                "/unban",
    "cmd_unwarn":               "/unwarn",
    "cmd_unmute":               "/smuta",
    "cmd_info":                 "/info",
    "cmd_silenceon":            "/silenzioon",
    "cmd_silenceoff":           "/silenziooff",
    "cmd_del":                  "/del",
    "cmd_staff":                "/staff",
    "cmd_rules":                "/regole",
    "cmd_pin":                  "/fissa",
    "cmd_unpin":                "/togli"
}
